# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
 platform :ios, '8.4'
# Uncomment this line if you're using Swift
use_frameworks!
pod 'KGFloatingDrawer', '~>0.2.0'
pod 'SnapKit', '~>0.15.0'
target 'Famtasy' do

end

target 'FamtasyTests' do

end

target 'FamtasyUITests' do

end

