# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!
pod 'KGFloatingDrawer', '~>0.2.0'

target 'Famtasy' do

end

target 'FamtasyTests' do

end

target 'FamtasyUITests' do

end

